workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-ssh

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER"
  coverage:
    when:
      branch: master
      event: push
  latest:
    image: docker
    storage_driver: overlay
    repo: plugins/ssh
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push
  develop:
    image: docker
    storage_driver: overlay
    repo: plugins/ssh
    tags: [ "develop" ]
    when:
      branch: develop
      event: push

plugin:
  name: SSH
  desc: Execute commands on a remote host through SSH
  type: deploy
  image: plugins/ssh
  labels:
    - deploy
    - ssh
