build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-ssh
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-ssh
    tag: develop
    when:
      branch: develop

plugin:
  name: SSH
  desc: Execute commands on a remote host through SSH
  type: deploy
  image: plugins/drone-ssh
  labels:
    - deploy
    - ssh
