build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-ssh
    when:
      branch: master

plugin:
  name: SSH
  desc: Use SSH to execute commands on a remote host
  type: deploy
  image: plugins/drone-ssh
  labels:
    - deploy
    - ssh
